// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1AfeZOe9NwFs9pwlTExBXQ89CL4NQ9WQ',
    appId: '1:101516272662:web:f462a3d193ffba680d4137',
    messagingSenderId: '101516272662',
    projectId: 'gestor-tarefas-d1455',
    authDomain: 'gestor-tarefas-d1455.firebaseapp.com',
    storageBucket: 'gestor-tarefas-d1455.firebasestorage.app',
    measurementId: 'G-HKQXT0RE0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW3Q6S86spKPPZSg_pYLM_fLt9J5Glulk',
    appId: '1:101516272662:android:df3fc6fe9919feca0d4137',
    messagingSenderId: '101516272662',
    projectId: 'gestor-tarefas-d1455',
    storageBucket: 'gestor-tarefas-d1455.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaqYSWkmgxMwEPZJ2fc1yE4aR2oIcYTMc',
    appId: '1:101516272662:ios:d59135de0f6c9d5a0d4137',
    messagingSenderId: '101516272662',
    projectId: 'gestor-tarefas-d1455',
    storageBucket: 'gestor-tarefas-d1455.firebasestorage.app',
    iosBundleId: 'com.example.gestorTarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaqYSWkmgxMwEPZJ2fc1yE4aR2oIcYTMc',
    appId: '1:101516272662:ios:d59135de0f6c9d5a0d4137',
    messagingSenderId: '101516272662',
    projectId: 'gestor-tarefas-d1455',
    storageBucket: 'gestor-tarefas-d1455.firebasestorage.app',
    iosBundleId: 'com.example.gestorTarefas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1AfeZOe9NwFs9pwlTExBXQ89CL4NQ9WQ',
    appId: '1:101516272662:web:15da6da845ab803c0d4137',
    messagingSenderId: '101516272662',
    projectId: 'gestor-tarefas-d1455',
    authDomain: 'gestor-tarefas-d1455.firebaseapp.com',
    storageBucket: 'gestor-tarefas-d1455.firebasestorage.app',
    measurementId: 'G-B56K36Z4CB',
  );
}
